### ISSUE TITLE
embed Groovy to avoid classpath problems and version conflicts

### ISSUE THREAD

**Issue by erisdev** [krsmes/GroovyBukkit#1]
Just sayin'. I'm having some trouble getting it to work at all because Groovy's API seems to be unstable. I'm getting the following error with Groovy 1.7.10, which I'm using because your forum post recommended 1.7.8 and I couldn't find it.

> 2011-08-27 02:20:42 [SEVERE] Error occurred while enabling GroovyBukkit v0.6.3.3 (Is it up to date?): org.codehaus.groovy.ast.ModuleNode.getStarImports()Ljava/util/List;
> java.lang.NoSuchMethodError: org.codehaus.groovy.ast.ModuleNode.getStarImports()Ljava/util/List;
>   at org.codehaus.groovy.ast.builder.AstBuilderTransformation.visit(AstBuilderTransformation.java:53)
>   at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:268)
>   at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:798)
>   at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:464)
>   at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:278)
>   at groovy.lang.GroovyShell.parseClass(GroovyShell.java:590)
>   at groovy.lang.GroovyShell.parse(GroovyShell.java:602)
>   at groovy.lang.GroovyShell.parse(GroovyShell.java:582)
>   at groovy.lang.GroovyShell.evaluate(GroovyShell.java:560)
>   at groovy.lang.GroovyShell.evaluate(GroovyShell.java:536)
>   at groovy.util.ProxyGenerator.instantiateAggregate(ProxyGenerator.java:237)
>   at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:105)
>   at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:95)
>   at org.codehaus.groovy.runtime.DefaultGroovyMethods.asType(DefaultGroovyMethods.java:4647)
>   at org.codehaus.groovy.runtime.dgm$37.doMethodInvoke(Unknown Source)
>   at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1049)
>   at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:880)
>   at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:733)
>   at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:724)
>   at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:163)
>   at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:586)
>   at net.krsmes.bukkit.groovy.GroovyBukkitConstructor.<init>(GroovyBukkitConstructor.groovy:18)
>   at net.krsmes.bukkit.groovy.GroovyPlugin.makeYaml(GroovyPlugin.java:243)
>   at net.krsmes.bukkit.groovy.GroovyPlugin.yamlLoad(GroovyPlugin.java:249)
>   at net.krsmes.bukkit.groovy.GroovyPlugin.loadData(GroovyPlugin.java:298)
>   at net.krsmes.bukkit.groovy.GroovyPlugin.onEnable(GroovyPlugin.java:97)
>   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
>   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:885)
>   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
>   at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
>   at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
>   at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
>   at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
>   at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
>   at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by erisdev** [comment]
Stupidly, I just noticed that this looks more like a bug in Groovy itself. At least, the error is nested pretty deep in the Groovy library.

**Comment by krsmes** [comment]
everything appears to be working fine with the latest version and groovy 1.8.2

**Comment by erisdev** [comment]
Cool, I might check it out later when Bukkit for 1.9 is a thing. I'm kinda burned out on Bukkit right now, though. :D
